# coding: utf-8

"""
    Crunchbase Enterprise API

    Crunchbase Enterprise API, 2021-07-16  # noqa: E501

    OpenAPI spec version: 1.0.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.entity_api import EntityApi  # noqa: E501
from swagger_client.rest import ApiException


class TestEntityApi(unittest.TestCase):
    """EntityApi unit test stubs"""

    def setUp(self):
        self.api = EntityApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_entities_acquisitions_entity_id_cards_card_id_get(self):
        """Test case for entities_acquisitions_entity_id_cards_card_id_get

        Lookup Acquisition's single card  # noqa: E501
        """
        pass

    def test_entities_acquisitions_entity_id_get(self):
        """Test case for entities_acquisitions_entity_id_get

        Lookup an Acquisition  # noqa: E501
        """
        pass

    def test_entities_addresses_entity_id_cards_card_id_get(self):
        """Test case for entities_addresses_entity_id_cards_card_id_get

        Lookup Address's single card  # noqa: E501
        """
        pass

    def test_entities_addresses_entity_id_get(self):
        """Test case for entities_addresses_entity_id_get

        Lookup an Address  # noqa: E501
        """
        pass

    def test_entities_categories_entity_id_cards_card_id_get(self):
        """Test case for entities_categories_entity_id_cards_card_id_get

        Lookup Category's single card  # noqa: E501
        """
        pass

    def test_entities_categories_entity_id_get(self):
        """Test case for entities_categories_entity_id_get

        Lookup a Category  # noqa: E501
        """
        pass

    def test_entities_category_groups_entity_id_cards_card_id_get(self):
        """Test case for entities_category_groups_entity_id_cards_card_id_get

        Lookup Category Group's single card  # noqa: E501
        """
        pass

    def test_entities_category_groups_entity_id_get(self):
        """Test case for entities_category_groups_entity_id_get

        Lookup a Category Group  # noqa: E501
        """
        pass

    def test_entities_degrees_entity_id_cards_card_id_get(self):
        """Test case for entities_degrees_entity_id_cards_card_id_get

        Lookup Degree's single card  # noqa: E501
        """
        pass

    def test_entities_degrees_entity_id_get(self):
        """Test case for entities_degrees_entity_id_get

        Lookup a Degree  # noqa: E501
        """
        pass

    def test_entities_event_appearances_entity_id_cards_card_id_get(self):
        """Test case for entities_event_appearances_entity_id_cards_card_id_get

        Lookup Event Appearance's single card  # noqa: E501
        """
        pass

    def test_entities_event_appearances_entity_id_get(self):
        """Test case for entities_event_appearances_entity_id_get

        Lookup an Event Appearance  # noqa: E501
        """
        pass

    def test_entities_events_entity_id_cards_card_id_get(self):
        """Test case for entities_events_entity_id_cards_card_id_get

        Lookup Event's single card  # noqa: E501
        """
        pass

    def test_entities_events_entity_id_get(self):
        """Test case for entities_events_entity_id_get

        Lookup an Event  # noqa: E501
        """
        pass

    def test_entities_funding_rounds_entity_id_cards_card_id_get(self):
        """Test case for entities_funding_rounds_entity_id_cards_card_id_get

        Lookup Funding Round's single card  # noqa: E501
        """
        pass

    def test_entities_funding_rounds_entity_id_get(self):
        """Test case for entities_funding_rounds_entity_id_get

        Lookup a Funding Round  # noqa: E501
        """
        pass

    def test_entities_funds_entity_id_cards_card_id_get(self):
        """Test case for entities_funds_entity_id_cards_card_id_get

        Lookup Fund's single card  # noqa: E501
        """
        pass

    def test_entities_funds_entity_id_get(self):
        """Test case for entities_funds_entity_id_get

        Lookup a Fund  # noqa: E501
        """
        pass

    def test_entities_investments_entity_id_cards_card_id_get(self):
        """Test case for entities_investments_entity_id_cards_card_id_get

        Lookup Investment's single card  # noqa: E501
        """
        pass

    def test_entities_investments_entity_id_get(self):
        """Test case for entities_investments_entity_id_get

        Lookup an Investment  # noqa: E501
        """
        pass

    def test_entities_ipos_entity_id_cards_card_id_get(self):
        """Test case for entities_ipos_entity_id_cards_card_id_get

        Lookup Ipo's single card  # noqa: E501
        """
        pass

    def test_entities_ipos_entity_id_get(self):
        """Test case for entities_ipos_entity_id_get

        Lookup an Ipo  # noqa: E501
        """
        pass

    def test_entities_jobs_entity_id_cards_card_id_get(self):
        """Test case for entities_jobs_entity_id_cards_card_id_get

        Lookup Job's single card  # noqa: E501
        """
        pass

    def test_entities_jobs_entity_id_get(self):
        """Test case for entities_jobs_entity_id_get

        Lookup a Job  # noqa: E501
        """
        pass

    def test_entities_locations_entity_id_cards_card_id_get(self):
        """Test case for entities_locations_entity_id_cards_card_id_get

        Lookup Location's single card  # noqa: E501
        """
        pass

    def test_entities_locations_entity_id_get(self):
        """Test case for entities_locations_entity_id_get

        Lookup a Location  # noqa: E501
        """
        pass

    def test_entities_organizations_entity_id_cards_card_id_get(self):
        """Test case for entities_organizations_entity_id_cards_card_id_get

        Lookup Organization's single card  # noqa: E501
        """
        pass

    def test_entities_organizations_entity_id_get(self):
        """Test case for entities_organizations_entity_id_get

        Lookup an Organization  # noqa: E501
        """
        pass

    def test_entities_ownerships_entity_id_cards_card_id_get(self):
        """Test case for entities_ownerships_entity_id_cards_card_id_get

        Lookup Ownership's single card  # noqa: E501
        """
        pass

    def test_entities_ownerships_entity_id_get(self):
        """Test case for entities_ownerships_entity_id_get

        Lookup an Ownership  # noqa: E501
        """
        pass

    def test_entities_people_entity_id_cards_card_id_get(self):
        """Test case for entities_people_entity_id_cards_card_id_get

        Lookup Person's single card  # noqa: E501
        """
        pass

    def test_entities_people_entity_id_get(self):
        """Test case for entities_people_entity_id_get

        Lookup a Person  # noqa: E501
        """
        pass

    def test_entities_press_references_entity_id_cards_card_id_get(self):
        """Test case for entities_press_references_entity_id_cards_card_id_get

        Lookup Press Reference's single card  # noqa: E501
        """
        pass

    def test_entities_press_references_entity_id_get(self):
        """Test case for entities_press_references_entity_id_get

        Lookup a Press Reference  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
