# coding: utf-8

"""
    Crunchbase Enterprise API

    Crunchbase Enterprise API, 2021-07-16  # noqa: E501

    OpenAPI spec version: 1.0.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.category_entity import CategoryEntity  # noqa: E501
from swagger_client.rest import ApiException


class TestCategoryEntity(unittest.TestCase):
    """CategoryEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCategoryEntity(self):
        """Test CategoryEntity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.category_entity.CategoryEntity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
