# coding: utf-8

"""
    Crunchbase Enterprise API

    Crunchbase Enterprise API, 2021-07-16  # noqa: E501

    OpenAPI spec version: 1.0.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.autocomplete_api import AutocompleteApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAutocompleteApi(unittest.TestCase):
    """AutocompleteApi unit test stubs"""

    def setUp(self):
        self.api = AutocompleteApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_autocompletes_get(self):
        """Test case for autocompletes_get

        Suggests matching Identifier entities based on the query and entity_def_ids provided.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
