# coding: utf-8

"""
    Crunchbase Enterprise API

    Crunchbase Enterprise API, 2021-07-16  # noqa: E501

    OpenAPI spec version: 1.0.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.ownership_entity import OwnershipEntity  # noqa: E501
from swagger_client.rest import ApiException


class TestOwnershipEntity(unittest.TestCase):
    """OwnershipEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOwnershipEntity(self):
        """Test OwnershipEntity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.ownership_entity.OwnershipEntity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
