# coding: utf-8

"""
    Crunchbase Enterprise API

    Crunchbase Enterprise API, 2021-07-16  # noqa: E501

    OpenAPI spec version: 1.0.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AddressEntityCards(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'event': 'list[Event]',
        'fields': 'Address',
        'organization': 'list[Organization]'
    }

    attribute_map = {
        'event': 'event',
        'fields': 'fields',
        'organization': 'organization'
    }

    def __init__(self, event=None, fields=None, organization=None):  # noqa: E501
        """AddressEntityCards - a model defined in Swagger"""  # noqa: E501
        self._event = None
        self._fields = None
        self._organization = None
        self.discriminator = None
        if event is not None:
            self.event = event
        if fields is not None:
            self.fields = fields
        if organization is not None:
            self.organization = organization

    @property
    def event(self):
        """Gets the event of this AddressEntityCards.  # noqa: E501


        :return: The event of this AddressEntityCards.  # noqa: E501
        :rtype: list[Event]
        """
        return self._event

    @event.setter
    def event(self, event):
        """Sets the event of this AddressEntityCards.


        :param event: The event of this AddressEntityCards.  # noqa: E501
        :type: list[Event]
        """

        self._event = event

    @property
    def fields(self):
        """Gets the fields of this AddressEntityCards.  # noqa: E501


        :return: The fields of this AddressEntityCards.  # noqa: E501
        :rtype: Address
        """
        return self._fields

    @fields.setter
    def fields(self, fields):
        """Sets the fields of this AddressEntityCards.


        :param fields: The fields of this AddressEntityCards.  # noqa: E501
        :type: Address
        """

        self._fields = fields

    @property
    def organization(self):
        """Gets the organization of this AddressEntityCards.  # noqa: E501


        :return: The organization of this AddressEntityCards.  # noqa: E501
        :rtype: list[Organization]
        """
        return self._organization

    @organization.setter
    def organization(self, organization):
        """Sets the organization of this AddressEntityCards.


        :param organization: The organization of this AddressEntityCards.  # noqa: E501
        :type: list[Organization]
        """

        self._organization = organization

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AddressEntityCards, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AddressEntityCards):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
