# coding: utf-8

"""
    Crunchbase Enterprise API

    Crunchbase Enterprise API, 2021-07-16  # noqa: E501

    OpenAPI spec version: 1.0.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DateWithPrecision(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'precision': 'str',
        'value': 'date'
    }

    attribute_map = {
        'precision': 'precision',
        'value': 'value'
    }

    def __init__(self, precision=None, value=None):  # noqa: E501
        """DateWithPrecision - a model defined in Swagger"""  # noqa: E501
        self._precision = None
        self._value = None
        self.discriminator = None
        self.precision = precision
        if value is not None:
            self.value = value

    @property
    def precision(self):
        """Gets the precision of this DateWithPrecision.  # noqa: E501


        :return: The precision of this DateWithPrecision.  # noqa: E501
        :rtype: str
        """
        return self._precision

    @precision.setter
    def precision(self, precision):
        """Sets the precision of this DateWithPrecision.


        :param precision: The precision of this DateWithPrecision.  # noqa: E501
        :type: str
        """
        if precision is None:
            raise ValueError("Invalid value for `precision`, must not be `None`")  # noqa: E501
        allowed_values = ["none", "year", "month", "day"]  # noqa: E501
        if precision not in allowed_values:
            raise ValueError(
                "Invalid value for `precision` ({0}), must be one of {1}"  # noqa: E501
                .format(precision, allowed_values)
            )

        self._precision = precision

    @property
    def value(self):
        """Gets the value of this DateWithPrecision.  # noqa: E501


        :return: The value of this DateWithPrecision.  # noqa: E501
        :rtype: date
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this DateWithPrecision.


        :param value: The value of this DateWithPrecision.  # noqa: E501
        :type: date
        """

        self._value = value

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DateWithPrecision, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DateWithPrecision):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
