# coding: utf-8

"""
    Crunchbase Enterprise API

    Crunchbase Enterprise API, 2021-07-16  # noqa: E501

    OpenAPI spec version: 1.0.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class FundEntityCards(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'fields': 'Fund',
        'investors': 'list[Principal]',
        'owner': 'list[Organization]',
        'press_references': 'list[PressReference]'
    }

    attribute_map = {
        'fields': 'fields',
        'investors': 'investors',
        'owner': 'owner',
        'press_references': 'press_references'
    }

    def __init__(self, fields=None, investors=None, owner=None, press_references=None):  # noqa: E501
        """FundEntityCards - a model defined in Swagger"""  # noqa: E501
        self._fields = None
        self._investors = None
        self._owner = None
        self._press_references = None
        self.discriminator = None
        if fields is not None:
            self.fields = fields
        if investors is not None:
            self.investors = investors
        if owner is not None:
            self.owner = owner
        if press_references is not None:
            self.press_references = press_references

    @property
    def fields(self):
        """Gets the fields of this FundEntityCards.  # noqa: E501


        :return: The fields of this FundEntityCards.  # noqa: E501
        :rtype: Fund
        """
        return self._fields

    @fields.setter
    def fields(self, fields):
        """Sets the fields of this FundEntityCards.


        :param fields: The fields of this FundEntityCards.  # noqa: E501
        :type: Fund
        """

        self._fields = fields

    @property
    def investors(self):
        """Gets the investors of this FundEntityCards.  # noqa: E501


        :return: The investors of this FundEntityCards.  # noqa: E501
        :rtype: list[Principal]
        """
        return self._investors

    @investors.setter
    def investors(self, investors):
        """Sets the investors of this FundEntityCards.


        :param investors: The investors of this FundEntityCards.  # noqa: E501
        :type: list[Principal]
        """

        self._investors = investors

    @property
    def owner(self):
        """Gets the owner of this FundEntityCards.  # noqa: E501


        :return: The owner of this FundEntityCards.  # noqa: E501
        :rtype: list[Organization]
        """
        return self._owner

    @owner.setter
    def owner(self, owner):
        """Sets the owner of this FundEntityCards.


        :param owner: The owner of this FundEntityCards.  # noqa: E501
        :type: list[Organization]
        """

        self._owner = owner

    @property
    def press_references(self):
        """Gets the press_references of this FundEntityCards.  # noqa: E501


        :return: The press_references of this FundEntityCards.  # noqa: E501
        :rtype: list[PressReference]
        """
        return self._press_references

    @press_references.setter
    def press_references(self, press_references):
        """Sets the press_references of this FundEntityCards.


        :param press_references: The press_references of this FundEntityCards.  # noqa: E501
        :type: list[PressReference]
        """

        self._press_references = press_references

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FundEntityCards, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FundEntityCards):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
