# coding: utf-8

"""
    Crunchbase Enterprise API

    Crunchbase Enterprise API, 2021-07-16  # noqa: E501

    OpenAPI spec version: 1.0.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class IpoEntityCards(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'fields': 'Ipo',
        'organization': 'list[Organization]',
        'press_references': 'list[PressReference]'
    }

    attribute_map = {
        'fields': 'fields',
        'organization': 'organization',
        'press_references': 'press_references'
    }

    def __init__(self, fields=None, organization=None, press_references=None):  # noqa: E501
        """IpoEntityCards - a model defined in Swagger"""  # noqa: E501
        self._fields = None
        self._organization = None
        self._press_references = None
        self.discriminator = None
        if fields is not None:
            self.fields = fields
        if organization is not None:
            self.organization = organization
        if press_references is not None:
            self.press_references = press_references

    @property
    def fields(self):
        """Gets the fields of this IpoEntityCards.  # noqa: E501


        :return: The fields of this IpoEntityCards.  # noqa: E501
        :rtype: Ipo
        """
        return self._fields

    @fields.setter
    def fields(self, fields):
        """Sets the fields of this IpoEntityCards.


        :param fields: The fields of this IpoEntityCards.  # noqa: E501
        :type: Ipo
        """

        self._fields = fields

    @property
    def organization(self):
        """Gets the organization of this IpoEntityCards.  # noqa: E501


        :return: The organization of this IpoEntityCards.  # noqa: E501
        :rtype: list[Organization]
        """
        return self._organization

    @organization.setter
    def organization(self, organization):
        """Sets the organization of this IpoEntityCards.


        :param organization: The organization of this IpoEntityCards.  # noqa: E501
        :type: list[Organization]
        """

        self._organization = organization

    @property
    def press_references(self):
        """Gets the press_references of this IpoEntityCards.  # noqa: E501


        :return: The press_references of this IpoEntityCards.  # noqa: E501
        :rtype: list[PressReference]
        """
        return self._press_references

    @press_references.setter
    def press_references(self, press_references):
        """Sets the press_references of this IpoEntityCards.


        :param press_references: The press_references of this IpoEntityCards.  # noqa: E501
        :type: list[PressReference]
        """

        self._press_references = press_references

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(IpoEntityCards, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IpoEntityCards):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
