# coding: utf-8

"""
    Crunchbase Enterprise API

    Crunchbase Enterprise API, 2021-07-16  # noqa: E501

    OpenAPI spec version: 1.0.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Money(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'currency': 'CurrencyEnum',
        'value_usd': 'int',
        'value': 'int'
    }

    attribute_map = {
        'currency': 'currency',
        'value_usd': 'value_usd',
        'value': 'value'
    }

    def __init__(self, currency=None, value_usd=None, value=None):  # noqa: E501
        """Money - a model defined in Swagger"""  # noqa: E501
        self._currency = None
        self._value_usd = None
        self._value = None
        self.discriminator = None
        self.currency = currency
        if value_usd is not None:
            self.value_usd = value_usd
        self.value = value

    @property
    def currency(self):
        """Gets the currency of this Money.  # noqa: E501


        :return: The currency of this Money.  # noqa: E501
        :rtype: CurrencyEnum
        """
        return self._currency

    @currency.setter
    def currency(self, currency):
        """Sets the currency of this Money.


        :param currency: The currency of this Money.  # noqa: E501
        :type: CurrencyEnum
        """
        if currency is None:
            raise ValueError("Invalid value for `currency`, must not be `None`")  # noqa: E501

        self._currency = currency

    @property
    def value_usd(self):
        """Gets the value_usd of this Money.  # noqa: E501


        :return: The value_usd of this Money.  # noqa: E501
        :rtype: int
        """
        return self._value_usd

    @value_usd.setter
    def value_usd(self, value_usd):
        """Sets the value_usd of this Money.


        :param value_usd: The value_usd of this Money.  # noqa: E501
        :type: int
        """

        self._value_usd = value_usd

    @property
    def value(self):
        """Gets the value of this Money.  # noqa: E501


        :return: The value of this Money.  # noqa: E501
        :rtype: int
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this Money.


        :param value: The value of this Money.  # noqa: E501
        :type: int
        """
        if value is None:
            raise ValueError("Invalid value for `value`, must not be `None`")  # noqa: E501

        self._value = value

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Money, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Money):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
